In [1]:
import numpy as np

In [57]:
x = np.logspace(np.log10(300), np.log10(60_000), num=9, endpoint=True)

In [58]:
int(x[-1])

60000

In [64]:
x 

array([  300.        ,   581.76823425,  1128.18092793,  2187.79942117,
        4242.64068712,  8227.44527029, 15954.88769083, 30940.15613164,
       60000.        ])

In [38]:
y = np.linspace(300, 60_000, num=11, endpoint=True)
y/3, len(y)

(array([  100.,  2090.,  4080.,  6070.,  8060., 10050., 12040., 14030.,
        16020., 18010., 20000.]),
 11)

In [6]:
ns = np.logspace(np.log10(300), 
                 np.log10(60_000), 
                 num=9, 
                 endpoint=True).astype(int)
tns = np.logspace(np.log10(100), 
                 np.log10(20_000), 
                 num=9, 
                 endpoint=True).astype(int)

print(len(ns))

ns//3, tns

9


(array([  100,   193,   376,   729,  1414,  2742,  5318, 10313, 20000]),
 array([  100,   193,   376,   729,  1414,  2742,  5318, 10313, 20000]))